[[Graphene]]
arch = "aarch64"
git-tree-sha1 = "e1434dbb9a335cdfc25b07a8c3c09f4e0ac9e374"
os = "macos"

    [[Graphene.download]]
    sha256 = "fa3e1d3461c7d7acfa76d7f2b8108709bdad459a5731ef980fb1d0e81566dd0c"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.aarch64-apple-darwin.tar.gz"
[[Graphene]]
arch = "aarch64"
git-tree-sha1 = "da2a2cd941f22a7dbf5d330941e43292a3e52947"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "fd335c2057237aeeede091e61eae78cea47944842e79925408cfbd924b8eed62"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.aarch64-linux-gnu.tar.gz"
[[Graphene]]
arch = "aarch64"
git-tree-sha1 = "52a0662572a2a3a177076c874e7ebba3fac0e8aa"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "6735835e5f73d004ab89c0860f2bad621f456d61d930b7cef6fa8a7027e26ad3"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.aarch64-linux-musl.tar.gz"
[[Graphene]]
arch = "aarch64"
git-tree-sha1 = "e596e5664cdc65670ebc2829e048ba8bdcda890c"
os = "freebsd"

    [[Graphene.download]]
    sha256 = "1794a4788c564deb99fb48ba62f3d8c96a1e70958e4010ab4fe5085a065ec8f5"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.aarch64-unknown-freebsd.tar.gz"
[[Graphene]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b9f74366c12e09365767938a5d8254badf6d1514"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "8699a9c336711d9732098c541442c5b4b72a07c041bbe739f00c71435ec4cc72"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.armv6l-linux-gnueabihf.tar.gz"
[[Graphene]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e08a8cbabfb473b13dd41383d8f4aa4ed51b233b"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "9498ec00d66ea02a7560e191d6131c5091af874a87308ffe037806a7ea0acd04"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.armv6l-linux-musleabihf.tar.gz"
[[Graphene]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "551945bd3dcabbbc77acdc919800c4d819ec7ecc"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "b86ddb03bb5d02b1d2d0f5df956d819eb23c6c7559d78c4057d5286cdd9f786f"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.armv7l-linux-gnueabihf.tar.gz"
[[Graphene]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2e51757eb8847e7720f8b78dd2083564590880ea"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "70601937bf84700f19c6cb5ec5d8f11164e1c5e405330d0468ed4e0d826b8183"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.armv7l-linux-musleabihf.tar.gz"
[[Graphene]]
arch = "i686"
git-tree-sha1 = "d3c91a84613aee2d220dc080014c7214f77df714"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "ec4bfd0093245a0d59c0b01f8794b5328c045840a9dbef38e0042ffd3480d616"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.i686-linux-gnu.tar.gz"
[[Graphene]]
arch = "i686"
git-tree-sha1 = "a447d2d4ddce3d121cf82bd895473b4d50c7a701"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "27135e7439b448a6b2cac2acf5bc3290b0a1d52e4fa1256129a0d517fd11f624"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.i686-linux-musl.tar.gz"
[[Graphene]]
arch = "i686"
git-tree-sha1 = "337a2b556775885daf5bbadb49fdb2d637724670"
os = "windows"

    [[Graphene.download]]
    sha256 = "cfb0682fe27e6a41b62aa5067036fd576fa1514d508cb3382229167c56acc2f1"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.i686-w64-mingw32.tar.gz"
[[Graphene]]
arch = "powerpc64le"
git-tree-sha1 = "f02535498e18beb037b47ab678fdcf75318322f2"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "76b778f0782a6651992cbee13aceeaa8da0e6f6560436d17a9fdf582b8da22bc"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.powerpc64le-linux-gnu.tar.gz"
[[Graphene]]
arch = "riscv64"
git-tree-sha1 = "1323bc08a48349d977cd9cbfb71eff1431b7c358"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "3c837f6162dba67728db350c12da8964d964be547720e5277d9521e1e21b75ff"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.riscv64-linux-gnu.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "0cb9af685c5dae9dec6b2e4a46e9502d678fc576"
os = "macos"

    [[Graphene.download]]
    sha256 = "ab49eec7dffaba09499e1b17edb2808b1c124b3071234c2f23ec410382d2dbe9"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.x86_64-apple-darwin.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "2eecfa403c0323adf86813b2d758002ec7ba0878"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "0aa0214554b97cd47a5d31af955809a1d442f5990cf06928d246f4f76ceb0149"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.x86_64-linux-gnu.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "2ad08847b3f908efb4dfac7b7f5285f9907e3335"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "31296085b304982dc21e994f907808643777c7df2d437dc604babb9508a54248"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.x86_64-linux-musl.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "db731d404daf42f64fe51856800e0c51d3a2c2e2"
os = "freebsd"

    [[Graphene.download]]
    sha256 = "92d11ce020098c9a8baafb0d0b325ff5e6c46b99a292a2db7695997158715f61"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.x86_64-unknown-freebsd.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "5506aff39de51dbf198d112b8deb32372c726de0"
os = "windows"

    [[Graphene.download]]
    sha256 = "f68b6277993eeae9e0e1c1f790c00370b7349093be43758c8d9ff70d3d15747d"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.8+0/Graphene.v1.10.8.x86_64-w64-mingw32.tar.gz"
