[[Graphene]]
arch = "aarch64"
git-tree-sha1 = "d5dd186e310243c15930018a05270e56b934da71"
os = "macos"

    [[Graphene.download]]
    sha256 = "03dd257c8b7df2fef4a39f3d3d2b55c3acf732543e8fb026da862edefe5dc193"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.aarch64-apple-darwin.tar.gz"
[[Graphene]]
arch = "aarch64"
git-tree-sha1 = "81966d2a27665c5b88ee0bd31283f8f0f564a01e"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "53b902bca4ecd794c6ba2a664bfb5ec5240244f7033372c1b43ebfe36adfd05c"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.aarch64-linux-gnu.tar.gz"
[[Graphene]]
arch = "aarch64"
git-tree-sha1 = "d60e9a4551e8fc98e6ce3616461544260e36ffeb"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "492ee65494ecc91e63866466ef6a75633ba65c522a0e3aa474903f1893cef743"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.aarch64-linux-musl.tar.gz"
[[Graphene]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d53111dd5609b3f5a0fd08da2a584c2e72051f17"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "7986ed74cc9d78ad007ea03eaaf534b0971983a073eedba6db42075d7abf31cf"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.armv6l-linux-gnueabihf.tar.gz"
[[Graphene]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "35fa47d84aeac136671dc1342920d8b57663ddb0"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "3795cedc2fb07f70f6f48a0666c7d1762a445ce2b4fe711778497a2131d1eb71"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.armv6l-linux-musleabihf.tar.gz"
[[Graphene]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e55f57a6cc1c11b94f514239701c80eeb89d12f6"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "920b357dcc326c426874cb0b015ade63cdde44f3afc260c4800c5c14a3194fd5"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.armv7l-linux-gnueabihf.tar.gz"
[[Graphene]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d72ddb7cd318c6b0b2850ccaaca091bd76aa8ed4"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "95e2bca1d07be871e74f8d26df85e24d73c9cc1396eb66f4ef44745e64735834"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.armv7l-linux-musleabihf.tar.gz"
[[Graphene]]
arch = "i686"
git-tree-sha1 = "d9e0d9c3081687743cd6dd67d4e21a6288191feb"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "30943c88419e5760a60b2a7bc4ff31d84003339644a29aede4c942cb74089841"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.i686-linux-gnu.tar.gz"
[[Graphene]]
arch = "i686"
git-tree-sha1 = "45e251a69bd2fed708c27980a141916c2bcca7ad"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "0dbc6762ad7d9ae467cf0c5bfe79ed9e2be001b74c2243b1cb42d6eae5f2ded6"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.i686-linux-musl.tar.gz"
[[Graphene]]
arch = "i686"
git-tree-sha1 = "bc9fda0dd7addfffc4a6d4dd0a77b5210e9dc695"
os = "windows"

    [[Graphene.download]]
    sha256 = "631526320b4ce99229be2eb528b45494f9570835b7d36af6fc4cc2ac4fc7bbf1"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.i686-w64-mingw32.tar.gz"
[[Graphene]]
arch = "powerpc64le"
git-tree-sha1 = "3d90bdd3b88871708a6a65523c8eb0a6ae2406e3"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "0040bf71cd367c16ef1ec4609aefcab98224fd3e07e7cc1b60be5c7e0271a3d4"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.powerpc64le-linux-gnu.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "c0a556cb3fb267666ad920028513de578bc941d5"
os = "macos"

    [[Graphene.download]]
    sha256 = "5a268646d38ace53cc69e76834d9fcd7b191293b70e1e5d8098f7f06823571ec"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.x86_64-apple-darwin.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "c837179fd6f03533451abc7b46808cb543e819c5"
libc = "glibc"
os = "linux"

    [[Graphene.download]]
    sha256 = "04b1536fc08cf1b0a0673eec11d315705eb2eb230db17f174c848053dbf0c0cd"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.x86_64-linux-gnu.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "5586e9ed5b7189984f187309eb24f40ef313f130"
libc = "musl"
os = "linux"

    [[Graphene.download]]
    sha256 = "027bc26445f6bd3c883cbd16f868564c601dcddd063652dca46bd693fc076c05"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.x86_64-linux-musl.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "6fe3e5e168308b045aa84e561b63aee9be0a409f"
os = "freebsd"

    [[Graphene.download]]
    sha256 = "d7013ee04b114b3da32f6dfc9e6780ced12e861d1d212cc174469ff84b582416"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.x86_64-unknown-freebsd.tar.gz"
[[Graphene]]
arch = "x86_64"
git-tree-sha1 = "035800bb2411aeee6ab9d8224c19d313c6463d0f"
os = "windows"

    [[Graphene.download]]
    sha256 = "450a37b3b0aa2949e545ad31fe9f5481041bfb0669ecb98a2def85424c2a91d7"
    url = "https://github.com/JuliaBinaryWrappers/Graphene_jll.jl/releases/download/Graphene-v1.10.6+0/Graphene.v1.10.6.x86_64-w64-mingw32.tar.gz"
