# Autogenerated wrapper script for Graphene_jll for armv6l-linux-musleabihf
export libgraphene

using Glib_jll
JLLWrappers.@generate_wrapper_header("Graphene")
JLLWrappers.@declare_library_product(libgraphene, "libgraphene-1.0.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Glib_jll)
    JLLWrappers.@init_library_product(
        libgraphene,
        "lib/libgraphene-1.0.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
