# Autogenerated wrapper script for Graphene_jll for i686-w64-mingw32
export libgraphene

using Glib_jll
JLLWrappers.@generate_wrapper_header("Graphene")
JLLWrappers.@declare_library_product(libgraphene, "libgraphene-1.0-0.dll")
function __init__()
    JLLWrappers.@generate_init_header(Glib_jll)
    JLLWrappers.@init_library_product(
        libgraphene,
        "bin\\libgraphene-1.0-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
