# Autogenerated wrapper script for Graphene_jll for x86_64-apple-darwin
export libgraphene

using Glib_jll
JLLWrappers.@generate_wrapper_header("Graphene")
JLLWrappers.@declare_library_product(libgraphene, "@rpath/libgraphene-1.0.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Glib_jll)
    JLLWrappers.@init_library_product(
        libgraphene,
        "lib/libgraphene-1.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
